# Generated by Django 6.0.7 on 2026-08-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر')),
                ('category', models.CharField(max_length=50, verbose_name='التصنيف')),
                ('image_url', models.URLField(verbose_name='رابط الصورة')),
            ],
        ),
    ]
