# Generated by Django 6.0.7 on 2026-08-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='العمر')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='اسم العطر')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.CharField(max_length=200, verbose_name='العنوان')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('Pending', 'قيد التجهيز'), ('Completed', 'مكتمل')], default='Pending', max_length=20, verbose_name='الحالة')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة'),
        ),
    ]
