# Generated by Django 6.0.7 on 2026-08-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم مكوّن الرائحة')),
            ],
            options={
                'verbose_name': 'مكوّن رائحة',
                'verbose_name_plural': 'مكونات الرائحة',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='perfume',
            name='scent_notes',
            field=models.ManyToManyField(blank=True, related_name='perfumes', to='shop.scentnote', verbose_name='مكونات الرائحة'),
        ),
    ]
